/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const AuthButton: typeof import('../components/auth/AuthButton')['AuthButton']
  const AuthShowcase: typeof import('../components/AuthShowcase')['default']
  const Button: typeof import('../components/ui/button')['Button']
  const Form: typeof import('../components/ui/form')['Form']
  const FormControl: typeof import('../components/ui/form')['FormControl']
  const FormDescription: typeof import('../components/ui/form')['FormDescription']
  const FormField: typeof import('../components/ui/form')['FormField']
  const FormItem: typeof import('../components/ui/form')['FormItem']
  const FormLabel: typeof import('../components/ui/form')['FormLabel']
  const FormMessage: typeof import('../components/ui/form')['FormMessage']
  const Header: typeof import('../components/Header')['default']
  const IconCar: typeof import('~icons/icon/car.jsx')['default']
  const IconCart: typeof import('~icons/icon/cart.jsx')['default']
  const IconGithub: typeof import('~icons/icon/github.jsx')['default']
  const IconGoogle: typeof import('~icons/icon/google.jsx')['default']
  const IconNotVisible: typeof import('~icons/icon/notVisible.jsx')['default']
  const IconVisible: typeof import('~icons/icon/visible.jsx')['default']
  const Input: typeof import('../components/ui/input')['Input']
  const Label: typeof import('../components/ui/label')['Label']
  const Layout: typeof import('../components/Layout')['default']
  const Link: typeof import('next/link')['default']
  const LoginForm: typeof import('../components/auth/LoginForm')['LoginForm']
  const NextDocument: typeof import('next/document')['Document']
  const NextDocumentHead: typeof import('next/document')['Head']
  const NextDocumentHtml: typeof import('next/document')['Html']
  const NextDocumentMain: typeof import('next/document')['Main']
  const NextDocumentScript: typeof import('next/document')['NextScript']
  const NextHead: typeof import('next/head')['default']
  const NextImage: typeof import('next/image')['default']
  const NextScript: typeof import('next/script')['default']
  const PasswordInput: typeof import('../components/ui/password-input')['PasswordInput']
  const Provider: typeof import('../components/Provider')['default']
  const SignUpForm: typeof import('../components/auth/SignUpForm')['SignUpForm']
  const SocialAuth: typeof import('../components/auth/SocialAuth')['SocialAuth']
  const buttonVariants: typeof import('../components/ui/button')['buttonVariants']
  const cn: typeof import('../lib/utils')['cn']
  const createRef: typeof import('react')['createRef']
  const createTRPCContext: typeof import('../lib/trpc/trpc')['createTRPCContext']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const loginSchema: typeof import('../schemas/auth')['loginSchema']
  const memo: typeof import('react')['memo']
  const mergeRouters: typeof import('../lib/trpc/trpc')['mergeRouters']
  const protectedProcedure: typeof import('../lib/trpc/trpc')['protectedProcedure']
  const publicProcedure: typeof import('../lib/trpc/trpc')['publicProcedure']
  const registerSchema: typeof import('../schemas/auth')['registerSchema']
  const router: typeof import('../lib/trpc/trpc')['router']
  const startTransition: typeof import('react')['startTransition']
  const trpc: typeof import('../lib/trpc/client')['trpc']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useFormField: typeof import('../components/ui/form')['useFormField']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useRouter: typeof import('next/navigation')['useRouter']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
  const useTranslation: typeof import('react-i18next')['useTranslation']
  const withRouter: typeof import('next/navigation')['withRouter']
  const z: typeof import('zod')['z']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { FC } from 'react'
  import('react')
  // @ts-ignore
  export type { useForm } from 'react-hook-form'
  import('react-hook-form')
  // @ts-ignore
  export type { User as PrismaUser, ToDoRecord as PrismaToDoRecord } from '@prisma/client'
  import('@prisma/client')
  // @ts-ignore
  export type { AppContext as NextAppContext, AppProps as NextAppProps } from 'next/app'
  import('next/app')
  // @ts-ignore
  export type { default as NextPage, GetServerSidePropsContext, InferGetServerSidePropsType } from 'next'
  import('next')
  // @ts-ignore
  export type { DocumentContext as NextDocumentContext } from 'next/document'
  import('next/document')
}
