export { CarInfoItem } from './ui/car-info-item'
export { CarInfoItemsWrapper } from './ui/car-info-items-wrapper'
export { carDetailsService } from './api/car-details.service'
export { processCarMileage, processCarTitle } from './lib/helpers'
export { type TCarDetailsRequest, type TCarDetailsResponse } from './api/schema'
