import '~/styles/globals.css'

import { Inter } from 'next/font/google'
import { type Metadata } from 'next'

import { TRPCReactProvider } from '~/trpc/TRPCReactProvider'

import { Toaster } from '~/components/ui/sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }]
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        {/* suppressHydrationWarning={true} was added to fix warning
      "Extra attributes from the server: data-new-gr-c-s-check-loaded,data-gr-ext-installed" comes from Grammarly
      */}
        <main className='relative flex flex-col min-h-screen'>
          <TRPCReactProvider>
            <div className='flex-grow flex-1'>
              {children}
            </div>
            <Toaster />
          </TRPCReactProvider>
        </main>
      </body>
    </html>
  )
}
