/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/health": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/billing/plans": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              plans: ({
                  priceId?: string | null;
                  name: string;
                  price: number;
                  /** @enum {string} */
                  recurring: "day" | "month" | "year";
                  restrictions: {
                    search?: number | null;
                    dealerMessage?: number | null;
                    scoutingReport?: number | null;
                    carScore?: number | null;
                    betterDeal?: number | null;
                  };
                })[];
            };
          };
        };
      };
    };
  };
  "/api/billing/checkout": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            priceId: string;
            /** @default false */
            useTrial?: boolean;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              session: string;
            };
          };
        };
      };
    };
  };
  "/api/billing/setup": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              session: string;
            };
          };
        };
      };
    };
  };
  "/api/car-chat/": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            carId: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              carChatId: string;
            };
          };
        };
      };
    };
  };
  "/api/car-chat-message/{carChatId}": {
    post: {
      parameters: {
        path: {
          carChatId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            message: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
  };
  "/api/dealer-chat/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              dealerChats: ({
                  /** Format: uuid */
                  id: string;
                  carId: string;
                  /** Format: uuid */
                  userId: string;
                  /** Format: email */
                  chatEmail: string;
                  /** Format: email */
                  dealerEmail?: string | null;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                  /** Format: uuid */
                  jobId?: string | null;
                  lastEmailMessageId?: string | null;
                  emailSubject?: string | null;
                  /** @default [] */
                  dealerAttachmentsIds?: string[];
                  message?: string | null;
                  unreadMessageCount: number;
                  carInfo: {
                    id: string;
                    make?: string | null;
                    model?: string | null;
                    year?: number | null;
                    mileage?: number | null;
                    price?: number | null;
                    images?: string[] | null;
                    historyOwners?: boolean | null;
                    historyAccidents?: boolean | null;
                    historyCleanTitle?: boolean | null;
                    historyPersonalUse?: boolean | null;
                    specialsExterior?: string | null;
                    specialsInterior?: string | null;
                    specialsFwd?: string | null;
                    specialsTransmission?: string | null;
                    specialsEngine?: string | null;
                    features?: string[] | null;
                    featuresDetails?: string[] | null;
                    vehicleBasicsFuelConsumption?: string | null;
                    vehicleBasicsLocation?: string | null;
                    vehicleBasicsVin?: string | null;
                    vehicleBasicsStockNumber?: string | null;
                    vehicleBasicsListedOn?: string | null;
                    dealerInfoWebsite?: string | null;
                    dealerInfoCity?: string | null;
                    dealerInfoStreet?: string | null;
                    dealerInfoPhone?: string | null;
                    coordinate?: number[] | null;
                    dealerName?: string | null;
                    moreFromSeller?: string | null;
                    trim?: string | null;
                    listingType?: string | null;
                    engineDescription?: string | null;
                    platformId?: string | null;
                    vin?: string | null;
                    isActive?: boolean | null;
                    featuresAll?: {
                        name: string;
                        category: string;
                      }[] | null;
                    platformDealerId?: string | null;
                    transmissionAdvanced?: string | null;
                    fuelTypeAdvanced?: string | null;
                    exteriorColorAdvanced?: string | null;
                    interiorColorAdvanced?: string | null;
                    vhrUrl?: string | null;
                    scoreAccident?: number | null;
                    scoreCar?: number | null;
                    scoreDeal?: number | null;
                    scoreFeatures?: number | null;
                    scoreMileage?: number | null;
                    scorePrice?: number | null;
                    scoreAccidentDetail?: string | null;
                    scoreFeaturesDetail?: string | null;
                    scoreMileageDetail?: string | null;
                    scorePriceDetail?: string | null;
                    scoreSummary?: string | null;
                    standOutFeatures?: {
                      [key: string]: {
                          feature: string;
                          featureDetails: string;
                        }[];
                    } | null;
                  };
                })[];
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            carId: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              dealerChat: {
                /** Format: uuid */
                id: string;
                carId: string;
                /** Format: uuid */
                userId: string;
                /** Format: email */
                chatEmail: string;
                /** Format: email */
                dealerEmail?: string | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                /** Format: uuid */
                jobId?: string | null;
                lastEmailMessageId?: string | null;
                emailSubject?: string | null;
                /** @default [] */
                dealerAttachmentsIds?: string[];
                carInfo: {
                  id: string;
                  make?: string | null;
                  model?: string | null;
                  year?: number | null;
                  mileage?: number | null;
                  price?: number | null;
                  images?: string[] | null;
                  historyOwners?: boolean | null;
                  historyAccidents?: boolean | null;
                  historyCleanTitle?: boolean | null;
                  historyPersonalUse?: boolean | null;
                  specialsExterior?: string | null;
                  specialsInterior?: string | null;
                  specialsFwd?: string | null;
                  specialsTransmission?: string | null;
                  specialsEngine?: string | null;
                  features?: string[] | null;
                  featuresDetails?: string[] | null;
                  vehicleBasicsFuelConsumption?: string | null;
                  vehicleBasicsLocation?: string | null;
                  vehicleBasicsVin?: string | null;
                  vehicleBasicsStockNumber?: string | null;
                  vehicleBasicsListedOn?: string | null;
                  dealerInfoWebsite?: string | null;
                  dealerInfoCity?: string | null;
                  dealerInfoStreet?: string | null;
                  dealerInfoPhone?: string | null;
                  coordinate?: number[] | null;
                  dealerName?: string | null;
                  moreFromSeller?: string | null;
                  trim?: string | null;
                  listingType?: string | null;
                  engineDescription?: string | null;
                  platformId?: string | null;
                  vin?: string | null;
                  isActive?: boolean | null;
                  featuresAll?: {
                      name: string;
                      category: string;
                    }[] | null;
                  platformDealerId?: string | null;
                  transmissionAdvanced?: string | null;
                  fuelTypeAdvanced?: string | null;
                  exteriorColorAdvanced?: string | null;
                  interiorColorAdvanced?: string | null;
                  vhrUrl?: string | null;
                  scoreAccident?: number | null;
                  scoreCar?: number | null;
                  scoreDeal?: number | null;
                  scoreFeatures?: number | null;
                  scoreMileage?: number | null;
                  scorePrice?: number | null;
                  scoreAccidentDetail?: string | null;
                  scoreFeaturesDetail?: string | null;
                  scoreMileageDetail?: string | null;
                  scorePriceDetail?: string | null;
                  scoreSummary?: string | null;
                  standOutFeatures?: {
                    [key: string]: {
                        feature: string;
                        featureDetails: string;
                      }[];
                  } | null;
                };
              };
            };
          };
        };
      };
    };
  };
  "/api/dealer-chat-message/{dealerChatId}": {
    post: {
      parameters: {
        path: {
          dealerChatId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            message: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              dealerChatMessage: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                dealerChatId: string;
                message: string;
                /** Format: date-time */
                lastSeenAt?: string | null;
                /** Format: uuid */
                userId?: string | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                /** @default [] */
                messageAttachments?: {
                    attachmentPath: string;
                    filename: string;
                    name: string;
                    type: string;
                  }[];
              };
            };
          };
        };
      };
    };
  };
  "/api/dealer-chat-message/{dealerChatMessageId}/view": {
    post: {
      parameters: {
        path: {
          dealerChatMessageId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/me/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              subId: string;
              email: string;
              name?: string | null;
            };
          };
        };
      };
    };
  };
  "/api/public/used-restriction-info": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              billingUsedRestrictionInfo: {
                search: {
                  limit: number | null;
                  count: number;
                  ids: string[];
                };
                scoutingReport: {
                  limit: number | null;
                  count: number;
                  ids: string[];
                };
                betterDeal: {
                  limit: number | null;
                  count: number;
                  ids: string[];
                };
                carScore: {
                  limit: number | null;
                  count: number;
                  ids: string[];
                };
                dealerMessage: {
                  limit: number | null;
                  count: number;
                  ids: string[];
                };
              };
            };
          };
        };
      };
    };
  };
  "/api/scouting-report/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              scoutingReports: ({
                  /** Format: uuid */
                  id: string;
                  /** @enum {string} */
                  status: "new" | "busy" | "error" | "done";
                  car: {
                    id: string;
                    make?: string | null;
                    model?: string | null;
                    year?: number | null;
                    mileage?: number | null;
                    price?: number | null;
                    images?: string[] | null;
                    features?: string[] | null;
                    body?: string | null;
                    color?: string | null;
                    shipping?: string | null;
                    dealerInfoStreet?: string | null;
                    dealerInfoCity?: string | null;
                    platformId?: string | null;
                    trim?: string | null;
                    vin?: string | null;
                    isActive?: boolean | null;
                    platformDealerId?: string | null;
                    coordinate?: number[] | null;
                    dealerName?: string | null;
                    vhrUrl?: string | null;
                    scoreCar?: number | null;
                    scoreDeal?: number | null;
                    standOutFeatures?: {
                      [key: string]: {
                          feature: string;
                          featureDetails: string;
                        }[];
                    } | null;
                  };
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                })[];
              limitCounter: {
                limit: number;
                usedCount: number;
              };
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            carId: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              scoutingReportId: string;
            };
          };
        };
      };
    };
  };
  "/api/scouting-report/{scoutingReportId}/download": {
    get: {
      parameters: {
        path: {
          scoutingReportId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              downloadUrl: string;
            };
          };
        };
      };
    };
  };
  "/api/scouting-report/{scoutingReportId}": {
    get: {
      parameters: {
        path: {
          scoutingReportId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              scoutingReport: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                status: "new" | "busy" | "error" | "done";
                car: {
                  id: string;
                  make?: string | null;
                  model?: string | null;
                  year?: number | null;
                  mileage?: number | null;
                  price?: number | null;
                  images?: string[] | null;
                  historyOwners?: boolean | null;
                  historyAccidents?: boolean | null;
                  historyCleanTitle?: boolean | null;
                  historyPersonalUse?: boolean | null;
                  specialsExterior?: string | null;
                  specialsInterior?: string | null;
                  specialsFwd?: string | null;
                  specialsTransmission?: string | null;
                  specialsEngine?: string | null;
                  features?: string[] | null;
                  featuresDetails?: string[] | null;
                  vehicleBasicsFuelConsumption?: string | null;
                  vehicleBasicsLocation?: string | null;
                  vehicleBasicsVin?: string | null;
                  vehicleBasicsStockNumber?: string | null;
                  vehicleBasicsListedOn?: string | null;
                  dealerInfoWebsite?: string | null;
                  dealerInfoCity?: string | null;
                  dealerInfoStreet?: string | null;
                  dealerInfoPhone?: string | null;
                  coordinate?: number[] | null;
                  dealerName?: string | null;
                  moreFromSeller?: string | null;
                  trim?: string | null;
                  listingType?: string | null;
                  engineDescription?: string | null;
                  platformId?: string | null;
                  vin?: string | null;
                  isActive?: boolean | null;
                  featuresAll?: {
                      name: string;
                      category: string;
                    }[] | null;
                  platformDealerId?: string | null;
                  transmissionAdvanced?: string | null;
                  fuelTypeAdvanced?: string | null;
                  exteriorColorAdvanced?: string | null;
                  interiorColorAdvanced?: string | null;
                  vhrUrl?: string | null;
                  scoreAccident?: number | null;
                  scoreCar?: number | null;
                  scoreDeal?: number | null;
                  scoreFeatures?: number | null;
                  scoreMileage?: number | null;
                  scorePrice?: number | null;
                  scoreAccidentDetail?: string | null;
                  scoreFeaturesDetail?: string | null;
                  scoreMileageDetail?: string | null;
                  scorePriceDetail?: string | null;
                  scoreSummary?: string | null;
                  standOutFeatures?: {
                    [key: string]: {
                        feature: string;
                        featureDetails: string;
                      }[];
                  } | null;
                };
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
            };
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          scoutingReportId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** @enum {boolean} */
              success: true;
            };
          };
        };
      };
    };
  };
  "/api/search-chat/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": ({
                /** Format: uuid */
                id: string;
                name: string;
                /** Format: uuid */
                parentId?: string | null;
                /** Format: uuid */
                userId?: string | null;
                metadata?: ({
                  /** @enum {string|null} */
                  currentGrouping?: "price_range" | "age" | "make_model" | "trim" | "mileage" | "body_style" | "score_car" | "score_deal" | null;
                  /** @enum {string} */
                  sortingField: "lastPrice" | "mileage" | "year" | "scoreCar" | "scoreDeal";
                  /** @enum {string} */
                  sortingDirection: "desc" | "asc";
                }) | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                /** Format: uuid */
                latestSearchResultId?: string | null;
              })[];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            message: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              searchResultId: string;
            };
          };
        };
      };
    };
  };
  "/api/search-chat/{chatId}/message": {
    post: {
      parameters: {
        path: {
          chatId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            message: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              searchResultId: string;
            };
          };
        };
      };
    };
  };
  "/api/search-result/history/{searchResultId}": {
    get: {
      parameters: {
        path: {
          searchResultId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              searchResultId: string;
              /** Format: uuid */
              chatId: string;
              requestMessage: string;
              responseMessage?: string | null;
              groupedCars?: (({
                  index: number;
                  name: string;
                  cars: ({
                      id: string;
                      make?: string | null;
                      model?: string | null;
                      year?: number | null;
                      mileage?: number | null;
                      price?: number | null;
                      images?: string[] | null;
                      features?: string[] | null;
                      body?: string | null;
                      color?: string | null;
                      shipping?: string | null;
                      dealerInfoStreet?: string | null;
                      dealerInfoCity?: string | null;
                      platformId?: string | null;
                      trim?: string | null;
                      vin?: string | null;
                      isActive?: boolean | null;
                      platformDealerId?: string | null;
                      coordinate?: number[] | null;
                      dealerName?: string | null;
                      vhrUrl?: string | null;
                      scoreCar?: number | null;
                      scoreDeal?: number | null;
                      standOutFeatures?: {
                        [key: string]: {
                            feature: string;
                            featureDetails: string;
                          }[];
                      } | null;
                    })[];
                })[]) | null;
              metadata?: ({
                availableGroupings?: string[] | null;
                availableSorting: string[];
                /** @enum {string|null} */
                currentGrouping?: "price_range" | "age" | "make_model" | "trim" | "mileage" | "body_style" | "score_car" | "score_deal" | null;
                /** @enum {string} */
                sortingField: "lastPrice" | "mileage" | "year" | "scoreCar" | "scoreDeal";
                /** @enum {string} */
                sortingDirection: "desc" | "asc";
                carIds?: string[];
                query?: {
                  [key: string]: unknown;
                } | null;
              }) | null;
              followUpQuestions?: string[] | null;
              searchResultIds?: string[] | null;
            };
          };
        };
      };
    };
  };
  "/api/webhooks/sendgrid/inbound-parse": {
    post: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/webhooks/stripe": {
    post: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/wishlist/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              cars: ({
                  id: string;
                  make?: string | null;
                  model?: string | null;
                  year?: number | null;
                  mileage?: number | null;
                  price?: number | null;
                  images?: string[] | null;
                  historyOwners?: boolean | null;
                  historyAccidents?: boolean | null;
                  historyCleanTitle?: boolean | null;
                  historyPersonalUse?: boolean | null;
                  specialsExterior?: string | null;
                  specialsInterior?: string | null;
                  specialsFwd?: string | null;
                  specialsTransmission?: string | null;
                  specialsEngine?: string | null;
                  features?: string[] | null;
                  featuresDetails?: string[] | null;
                  vehicleBasicsFuelConsumption?: string | null;
                  vehicleBasicsLocation?: string | null;
                  vehicleBasicsVin?: string | null;
                  vehicleBasicsStockNumber?: string | null;
                  vehicleBasicsListedOn?: string | null;
                  dealerInfoWebsite?: string | null;
                  dealerInfoCity?: string | null;
                  dealerInfoStreet?: string | null;
                  dealerInfoPhone?: string | null;
                  coordinate?: number[] | null;
                  dealerName?: string | null;
                  moreFromSeller?: string | null;
                  trim?: string | null;
                  listingType?: string | null;
                  engineDescription?: string | null;
                  platformId?: string | null;
                  vin?: string | null;
                  isActive?: boolean | null;
                  featuresAll?: {
                      name: string;
                      category: string;
                    }[] | null;
                  platformDealerId?: string | null;
                  transmissionAdvanced?: string | null;
                  fuelTypeAdvanced?: string | null;
                  exteriorColorAdvanced?: string | null;
                  interiorColorAdvanced?: string | null;
                  vhrUrl?: string | null;
                  scoreAccident?: number | null;
                  scoreCar?: number | null;
                  scoreDeal?: number | null;
                  scoreFeatures?: number | null;
                  scoreMileage?: number | null;
                  scorePrice?: number | null;
                  scoreAccidentDetail?: string | null;
                  scoreFeaturesDetail?: string | null;
                  scoreMileageDetail?: string | null;
                  scorePriceDetail?: string | null;
                  scoreSummary?: string | null;
                  standOutFeatures?: {
                    [key: string]: {
                        feature: string;
                        featureDetails: string;
                      }[];
                  } | null;
                  /** Format: date-time */
                  createdAt: string;
                })[];
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            carId: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    delete: {
      requestBody: {
        content: {
          "application/json": {
            carId: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/wishlist/message": {
    post: {
      parameters: {
        query?: {
          sortingField?: "createdAt" | "price";
          sortingDirection?: "desc" | "asc";
        };
      };
      requestBody: {
        content: {
          "application/json": {
            message: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              responseMessage: string;
            };
          };
        };
      };
    };
  };
  "/api/auth/magic-link/": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            name?: string | null;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/billing/profile/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              /** Format: uuid */
              userId: string;
              stripeCustomerId: string;
              restrictions: {
                search: {
                  amount: number | null;
                  /** @enum {string} */
                  period: "month" | "year" | "unlimited" | "day";
                };
                scoutingReport: {
                  amount: number | null;
                  /** @enum {string} */
                  period: "month" | "year" | "unlimited" | "day";
                };
                betterDeal: {
                  amount: number | null;
                  /** @enum {string} */
                  period: "month" | "year" | "unlimited" | "day";
                };
                carScore: {
                  amount: number | null;
                  /** @enum {string} */
                  period: "month" | "year" | "unlimited" | "day";
                };
                dealerMessage: {
                  amount: number | null;
                  /** @enum {string} */
                  period: "month" | "year" | "unlimited" | "day";
                };
              };
              subscriptionId?: string | null;
              /** @enum {string} */
              status: "okay" | "canceled" | "failed" | "incomplete";
              /** Format: date-time */
              expiredAt?: string | null;
              /** Format: date-time */
              trialStartAt?: string | null;
              /** Format: date-time */
              trialEndAt?: string | null;
              /** @enum {string} */
              plan: "Free" | "Premium";
              isTrial: boolean;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
    };
  };
  "/api/billing/profile/used-restriction-info": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              billingUsedRestrictionInfo: {
                search: {
                  limit: number | null;
                  count: number;
                  ids: string[];
                };
                scoutingReport: {
                  limit: number | null;
                  count: number;
                  ids: string[];
                };
                betterDeal: {
                  limit: number | null;
                  count: number;
                  ids: string[];
                };
                carScore: {
                  limit: number | null;
                  count: number;
                  ids: string[];
                };
                dealerMessage: {
                  limit: number | null;
                  count: number;
                  ids: string[];
                };
              };
            };
          };
        };
      };
    };
  };
  "/api/billing/profile/payment-method": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": ({
              brand?: string | null;
              displayBrand?: string | null;
              last4?: string | null;
            }) | null;
          };
        };
      };
    };
  };
  "/api/billing/profile/cancel": {
    post: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** @enum {boolean} */
              success: true;
            };
          };
        };
      };
    };
  };
  "/api/billing/profile/renewal": {
    post: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** @enum {boolean} */
              success: true;
            };
          };
        };
      };
    };
  };
  "/api/billing/profile/downgrade": {
    post: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** @enum {boolean} */
              success: true;
            };
          };
        };
      };
    };
  };
  "/api/car/{carId}/": {
    get: {
      parameters: {
        path: {
          carId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              car: {
                id: string;
                make?: string | null;
                model?: string | null;
                year?: number | null;
                mileage?: number | null;
                price?: number | null;
                images?: string[] | null;
                historyOwners?: boolean | null;
                historyAccidents?: boolean | null;
                historyCleanTitle?: boolean | null;
                historyPersonalUse?: boolean | null;
                specialsExterior?: string | null;
                specialsInterior?: string | null;
                specialsFwd?: string | null;
                specialsTransmission?: string | null;
                specialsEngine?: string | null;
                features?: string[] | null;
                featuresDetails?: string[] | null;
                vehicleBasicsFuelConsumption?: string | null;
                vehicleBasicsLocation?: string | null;
                vehicleBasicsVin?: string | null;
                vehicleBasicsStockNumber?: string | null;
                vehicleBasicsListedOn?: string | null;
                dealerInfoWebsite?: string | null;
                dealerInfoCity?: string | null;
                dealerInfoStreet?: string | null;
                dealerInfoPhone?: string | null;
                coordinate?: number[] | null;
                dealerName?: string | null;
                moreFromSeller?: string | null;
                trim?: string | null;
                listingType?: string | null;
                engineDescription?: string | null;
                platformId?: string | null;
                vin?: string | null;
                isActive?: boolean | null;
                featuresAll?: {
                    name: string;
                    category: string;
                  }[] | null;
                platformDealerId?: string | null;
                transmissionAdvanced?: string | null;
                fuelTypeAdvanced?: string | null;
                exteriorColorAdvanced?: string | null;
                interiorColorAdvanced?: string | null;
                vhrUrl?: string | null;
                scoreAccident?: number | null;
                scoreCar?: number | null;
                scoreDeal?: number | null;
                scoreFeatures?: number | null;
                scoreMileage?: number | null;
                scorePrice?: number | null;
                scoreAccidentDetail?: string | null;
                scoreFeaturesDetail?: string | null;
                scoreMileageDetail?: string | null;
                scorePriceDetail?: string | null;
                scoreSummary?: string | null;
                standOutFeatures?: {
                  [key: string]: {
                      feature: string;
                      featureDetails: string;
                    }[];
                } | null;
              };
            };
          };
        };
      };
    };
  };
  "/api/car/{carId}/better-deal": {
    get: {
      parameters: {
        query?: {
          grouping?: "price_range" | "age" | "make_model" | "trim" | "mileage" | "body_style" | "score_car" | "score_deal" | null;
        };
        path: {
          carId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              count: number;
              /** Format: uuid */
              betterDealId: string;
            };
          };
        };
      };
    };
  };
  "/api/car/{carId}/better-deal/{betterDealId}": {
    get: {
      parameters: {
        path: {
          carId: string;
          betterDealId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              groupedCars?: (({
                  index: number;
                  name: string;
                  cars: ({
                      id: string;
                      make?: string | null;
                      model?: string | null;
                      year?: number | null;
                      mileage?: number | null;
                      price?: number | null;
                      images?: string[] | null;
                      features?: string[] | null;
                      body?: string | null;
                      color?: string | null;
                      shipping?: string | null;
                      dealerInfoStreet?: string | null;
                      dealerInfoCity?: string | null;
                      platformId?: string | null;
                      trim?: string | null;
                      vin?: string | null;
                      isActive?: boolean | null;
                      platformDealerId?: string | null;
                      coordinate?: number[] | null;
                      dealerName?: string | null;
                      vhrUrl?: string | null;
                      scoreCar?: number | null;
                      scoreDeal?: number | null;
                      standOutFeatures?: {
                        [key: string]: {
                            feature: string;
                            featureDetails: string;
                          }[];
                      } | null;
                    })[];
                })[]) | null;
            };
          };
        };
      };
    };
  };
  "/api/car/{carId}/car-scores": {
    get: {
      parameters: {
        path: {
          carId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              car: {
                scoreAccident?: number | null;
                scoreCar?: number | null;
                scoreDeal?: number | null;
                scoreFeatures?: number | null;
                scoreMileage?: number | null;
                scorePrice?: number | null;
                scoreAccidentDetail?: string | null;
                scoreFeaturesDetail?: string | null;
                scoreMileageDetail?: string | null;
                scorePriceDetail?: string | null;
                scoreSummary?: string | null;
              };
            };
          };
        };
      };
    };
  };
  "/api/dealer-chat/{dealerChatId}/": {
    get: {
      parameters: {
        path: {
          dealerChatId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              messages: ({
                  /** Format: uuid */
                  id: string;
                  /** Format: uuid */
                  dealerChatId: string;
                  message: string;
                  /** Format: date-time */
                  lastSeenAt?: string | null;
                  /** Format: uuid */
                  userId?: string | null;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                  /** @default [] */
                  messageAttachments?: {
                      attachmentPath: string;
                      filename: string;
                      name: string;
                      type: string;
                    }[];
                })[];
            };
          };
        };
      };
    };
  };
  "/api/dealer-chat/{dealerChatId}/negotiation": {
    post: {
      parameters: {
        path: {
          dealerChatId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            message: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              response: string;
            };
          };
        };
      };
    };
  };
  "/api/public/search-chat/": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            message: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              searchResultId: string;
            };
          };
        };
      };
    };
  };
  "/api/public/search-chat/{chatId}/message": {
    post: {
      parameters: {
        path: {
          chatId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            message: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              searchResultId: string;
            };
          };
        };
      };
    };
  };
  "/api/public/search-result/history/{searchResultId}": {
    get: {
      parameters: {
        path: {
          searchResultId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              searchResultId: string;
              /** Format: uuid */
              chatId: string;
              requestMessage: string;
              responseMessage?: string | null;
              groupedCars?: (({
                  index: number;
                  name: string;
                  cars: ({
                      id: string;
                      make?: string | null;
                      model?: string | null;
                      year?: number | null;
                      mileage?: number | null;
                      price?: number | null;
                      images?: string[] | null;
                      features?: string[] | null;
                      body?: string | null;
                      color?: string | null;
                      shipping?: string | null;
                      dealerInfoStreet?: string | null;
                      dealerInfoCity?: string | null;
                      platformId?: string | null;
                      trim?: string | null;
                      vin?: string | null;
                      isActive?: boolean | null;
                      platformDealerId?: string | null;
                      coordinate?: number[] | null;
                      dealerName?: string | null;
                      vhrUrl?: string | null;
                      scoreCar?: number | null;
                      scoreDeal?: number | null;
                      standOutFeatures?: {
                        [key: string]: {
                            feature: string;
                            featureDetails: string;
                          }[];
                      } | null;
                    })[];
                })[]) | null;
              metadata?: ({
                availableGroupings?: string[] | null;
                availableSorting: string[];
                /** @enum {string|null} */
                currentGrouping?: "price_range" | "age" | "make_model" | "trim" | "mileage" | "body_style" | "score_car" | "score_deal" | null;
                /** @enum {string} */
                sortingField: "lastPrice" | "mileage" | "year" | "scoreCar" | "scoreDeal";
                /** @enum {string} */
                sortingDirection: "desc" | "asc";
                carIds?: string[];
                query?: {
                  [key: string]: unknown;
                } | null;
              }) | null;
              followUpQuestions?: string[] | null;
              searchResultIds?: string[] | null;
            };
          };
        };
      };
    };
  };
  "/api/search-chat/{chatId}/": {
    delete: {
      parameters: {
        path: {
          chatId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/search-result/{searchResultId}/": {
    get: {
      parameters: {
        path: {
          searchResultId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              searchResultId: string;
              /** Format: uuid */
              chatId: string;
              requestMessage: string;
              responseMessage?: string | null;
              groupedCars?: (({
                  index: number;
                  name: string;
                  cars: ({
                      id: string;
                      make?: string | null;
                      model?: string | null;
                      year?: number | null;
                      mileage?: number | null;
                      price?: number | null;
                      images?: string[] | null;
                      features?: string[] | null;
                      body?: string | null;
                      color?: string | null;
                      shipping?: string | null;
                      dealerInfoStreet?: string | null;
                      dealerInfoCity?: string | null;
                      platformId?: string | null;
                      trim?: string | null;
                      vin?: string | null;
                      isActive?: boolean | null;
                      platformDealerId?: string | null;
                      coordinate?: number[] | null;
                      dealerName?: string | null;
                      vhrUrl?: string | null;
                      scoreCar?: number | null;
                      scoreDeal?: number | null;
                      standOutFeatures?: {
                        [key: string]: {
                            feature: string;
                            featureDetails: string;
                          }[];
                      } | null;
                    })[];
                })[]) | null;
              metadata?: ({
                availableGroupings?: string[] | null;
                availableSorting: string[];
                /** @enum {string|null} */
                currentGrouping?: "price_range" | "age" | "make_model" | "trim" | "mileage" | "body_style" | "score_car" | "score_deal" | null;
                /** @enum {string} */
                sortingField: "lastPrice" | "mileage" | "year" | "scoreCar" | "scoreDeal";
                /** @enum {string} */
                sortingDirection: "desc" | "asc";
                carIds?: string[];
                query?: {
                  [key: string]: unknown;
                } | null;
              }) | null;
              followUpQuestions?: string[] | null;
              searchResultIds?: string[] | null;
            };
          };
        };
      };
    };
  };
  "/api/search-result/{searchResultId}/grouping": {
    get: {
      parameters: {
        query: {
          currentGrouping: "price_range" | "age" | "make_model" | "trim" | "mileage" | "body_style" | "score_car" | "score_deal";
        };
        path: {
          searchResultId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              searchResultId: string;
              /** Format: uuid */
              chatId: string;
              requestMessage: string;
              responseMessage?: string | null;
              groupedCars?: (({
                  index: number;
                  name: string;
                  cars: ({
                      id: string;
                      make?: string | null;
                      model?: string | null;
                      year?: number | null;
                      mileage?: number | null;
                      price?: number | null;
                      images?: string[] | null;
                      features?: string[] | null;
                      body?: string | null;
                      color?: string | null;
                      shipping?: string | null;
                      dealerInfoStreet?: string | null;
                      dealerInfoCity?: string | null;
                      platformId?: string | null;
                      trim?: string | null;
                      vin?: string | null;
                      isActive?: boolean | null;
                      platformDealerId?: string | null;
                      coordinate?: number[] | null;
                      dealerName?: string | null;
                      vhrUrl?: string | null;
                      scoreCar?: number | null;
                      scoreDeal?: number | null;
                      standOutFeatures?: {
                        [key: string]: {
                            feature: string;
                            featureDetails: string;
                          }[];
                      } | null;
                    })[];
                })[]) | null;
              metadata?: ({
                availableGroupings?: string[] | null;
                availableSorting: string[];
                /** @enum {string|null} */
                currentGrouping?: "price_range" | "age" | "make_model" | "trim" | "mileage" | "body_style" | "score_car" | "score_deal" | null;
                /** @enum {string} */
                sortingField: "lastPrice" | "mileage" | "year" | "scoreCar" | "scoreDeal";
                /** @enum {string} */
                sortingDirection: "desc" | "asc";
                carIds?: string[];
                query?: {
                  [key: string]: unknown;
                } | null;
              }) | null;
              followUpQuestions?: string[] | null;
              searchResultIds?: string[] | null;
            };
          };
        };
      };
    };
  };
  "/api/search-result/{searchResultId}/sorting": {
    get: {
      parameters: {
        query: {
          sortingField: "lastPrice" | "mileage" | "year" | "scoreCar" | "scoreDeal";
          sortingDirection: "desc" | "asc";
        };
        path: {
          searchResultId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              searchResultId: string;
              /** Format: uuid */
              chatId: string;
              requestMessage: string;
              responseMessage?: string | null;
              groupedCars?: (({
                  index: number;
                  name: string;
                  cars: ({
                      id: string;
                      make?: string | null;
                      model?: string | null;
                      year?: number | null;
                      mileage?: number | null;
                      price?: number | null;
                      images?: string[] | null;
                      features?: string[] | null;
                      body?: string | null;
                      color?: string | null;
                      shipping?: string | null;
                      dealerInfoStreet?: string | null;
                      dealerInfoCity?: string | null;
                      platformId?: string | null;
                      trim?: string | null;
                      vin?: string | null;
                      isActive?: boolean | null;
                      platformDealerId?: string | null;
                      coordinate?: number[] | null;
                      dealerName?: string | null;
                      vhrUrl?: string | null;
                      scoreCar?: number | null;
                      scoreDeal?: number | null;
                      standOutFeatures?: {
                        [key: string]: {
                            feature: string;
                            featureDetails: string;
                          }[];
                      } | null;
                    })[];
                })[]) | null;
              metadata?: ({
                availableGroupings?: string[] | null;
                availableSorting: string[];
                /** @enum {string|null} */
                currentGrouping?: "price_range" | "age" | "make_model" | "trim" | "mileage" | "body_style" | "score_car" | "score_deal" | null;
                /** @enum {string} */
                sortingField: "lastPrice" | "mileage" | "year" | "scoreCar" | "scoreDeal";
                /** @enum {string} */
                sortingDirection: "desc" | "asc";
                carIds?: string[];
                query?: {
                  [key: string]: unknown;
                } | null;
              }) | null;
              followUpQuestions?: string[] | null;
              searchResultIds?: string[] | null;
            };
          };
        };
      };
    };
  };
  "/api/search-result/{searchResultId}/follow-up-questions": {
    get: {
      parameters: {
        path: {
          searchResultId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              questions: string[];
            };
          };
        };
      };
    };
  };
  "/api/public/car/{carId}/": {
    get: {
      parameters: {
        path: {
          carId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              car: {
                id: string;
                make?: string | null;
                model?: string | null;
                year?: number | null;
                mileage?: number | null;
                price?: number | null;
                images?: string[] | null;
                historyOwners?: boolean | null;
                historyAccidents?: boolean | null;
                historyCleanTitle?: boolean | null;
                historyPersonalUse?: boolean | null;
                specialsExterior?: string | null;
                specialsInterior?: string | null;
                specialsFwd?: string | null;
                specialsTransmission?: string | null;
                specialsEngine?: string | null;
                features?: string[] | null;
                featuresDetails?: string[] | null;
                vehicleBasicsFuelConsumption?: string | null;
                vehicleBasicsLocation?: string | null;
                vehicleBasicsVin?: string | null;
                vehicleBasicsStockNumber?: string | null;
                vehicleBasicsListedOn?: string | null;
                dealerInfoWebsite?: string | null;
                dealerInfoCity?: string | null;
                dealerInfoStreet?: string | null;
                dealerInfoPhone?: string | null;
                coordinate?: number[] | null;
                dealerName?: string | null;
                moreFromSeller?: string | null;
                trim?: string | null;
                listingType?: string | null;
                engineDescription?: string | null;
                platformId?: string | null;
                vin?: string | null;
                isActive?: boolean | null;
                featuresAll?: {
                    name: string;
                    category: string;
                  }[] | null;
                platformDealerId?: string | null;
                transmissionAdvanced?: string | null;
                fuelTypeAdvanced?: string | null;
                exteriorColorAdvanced?: string | null;
                interiorColorAdvanced?: string | null;
                vhrUrl?: string | null;
                scoreAccident?: number | null;
                scoreCar?: number | null;
                scoreDeal?: number | null;
                scoreFeatures?: number | null;
                scoreMileage?: number | null;
                scorePrice?: number | null;
                scoreAccidentDetail?: string | null;
                scoreFeaturesDetail?: string | null;
                scoreMileageDetail?: string | null;
                scorePriceDetail?: string | null;
                scoreSummary?: string | null;
                standOutFeatures?: {
                  [key: string]: {
                      feature: string;
                      featureDetails: string;
                    }[];
                } | null;
              };
            };
          };
        };
      };
    };
  };
  "/api/public/search-result/{searchResultId}/": {
    get: {
      parameters: {
        path: {
          searchResultId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              searchResultId: string;
              /** Format: uuid */
              chatId: string;
              requestMessage: string;
              responseMessage?: string | null;
              groupedCars?: (({
                  index: number;
                  name: string;
                  cars: ({
                      id: string;
                      make?: string | null;
                      model?: string | null;
                      year?: number | null;
                      mileage?: number | null;
                      price?: number | null;
                      images?: string[] | null;
                      features?: string[] | null;
                      body?: string | null;
                      color?: string | null;
                      shipping?: string | null;
                      dealerInfoStreet?: string | null;
                      dealerInfoCity?: string | null;
                      platformId?: string | null;
                      trim?: string | null;
                      vin?: string | null;
                      isActive?: boolean | null;
                      platformDealerId?: string | null;
                      coordinate?: number[] | null;
                      dealerName?: string | null;
                      vhrUrl?: string | null;
                      scoreCar?: number | null;
                      scoreDeal?: number | null;
                      standOutFeatures?: {
                        [key: string]: {
                            feature: string;
                            featureDetails: string;
                          }[];
                      } | null;
                    })[];
                })[]) | null;
              metadata?: ({
                availableGroupings?: string[] | null;
                availableSorting: string[];
                /** @enum {string|null} */
                currentGrouping?: "price_range" | "age" | "make_model" | "trim" | "mileage" | "body_style" | "score_car" | "score_deal" | null;
                /** @enum {string} */
                sortingField: "lastPrice" | "mileage" | "year" | "scoreCar" | "scoreDeal";
                /** @enum {string} */
                sortingDirection: "desc" | "asc";
                carIds?: string[];
                query?: {
                  [key: string]: unknown;
                } | null;
              }) | null;
              followUpQuestions?: string[] | null;
              searchResultIds?: string[] | null;
            };
          };
        };
      };
    };
  };
  "/api/public/search-result/{searchResultId}/grouping": {
    get: {
      parameters: {
        query: {
          currentGrouping: "price_range" | "age" | "make_model" | "trim" | "mileage" | "body_style" | "score_car" | "score_deal";
        };
        path: {
          searchResultId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              searchResultId: string;
              /** Format: uuid */
              chatId: string;
              requestMessage: string;
              responseMessage?: string | null;
              groupedCars?: (({
                  index: number;
                  name: string;
                  cars: ({
                      id: string;
                      make?: string | null;
                      model?: string | null;
                      year?: number | null;
                      mileage?: number | null;
                      price?: number | null;
                      images?: string[] | null;
                      features?: string[] | null;
                      body?: string | null;
                      color?: string | null;
                      shipping?: string | null;
                      dealerInfoStreet?: string | null;
                      dealerInfoCity?: string | null;
                      platformId?: string | null;
                      trim?: string | null;
                      vin?: string | null;
                      isActive?: boolean | null;
                      platformDealerId?: string | null;
                      coordinate?: number[] | null;
                      dealerName?: string | null;
                      vhrUrl?: string | null;
                      scoreCar?: number | null;
                      scoreDeal?: number | null;
                      standOutFeatures?: {
                        [key: string]: {
                            feature: string;
                            featureDetails: string;
                          }[];
                      } | null;
                    })[];
                })[]) | null;
              metadata?: ({
                availableGroupings?: string[] | null;
                availableSorting: string[];
                /** @enum {string|null} */
                currentGrouping?: "price_range" | "age" | "make_model" | "trim" | "mileage" | "body_style" | "score_car" | "score_deal" | null;
                /** @enum {string} */
                sortingField: "lastPrice" | "mileage" | "year" | "scoreCar" | "scoreDeal";
                /** @enum {string} */
                sortingDirection: "desc" | "asc";
                carIds?: string[];
                query?: {
                  [key: string]: unknown;
                } | null;
              }) | null;
              followUpQuestions?: string[] | null;
              searchResultIds?: string[] | null;
            };
          };
        };
      };
    };
  };
  "/api/public/search-result/{searchResultId}/sorting": {
    get: {
      parameters: {
        query: {
          sortingField: "lastPrice" | "mileage" | "year" | "scoreCar" | "scoreDeal";
          sortingDirection: "desc" | "asc";
        };
        path: {
          searchResultId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              searchResultId: string;
              /** Format: uuid */
              chatId: string;
              requestMessage: string;
              responseMessage?: string | null;
              groupedCars?: (({
                  index: number;
                  name: string;
                  cars: ({
                      id: string;
                      make?: string | null;
                      model?: string | null;
                      year?: number | null;
                      mileage?: number | null;
                      price?: number | null;
                      images?: string[] | null;
                      features?: string[] | null;
                      body?: string | null;
                      color?: string | null;
                      shipping?: string | null;
                      dealerInfoStreet?: string | null;
                      dealerInfoCity?: string | null;
                      platformId?: string | null;
                      trim?: string | null;
                      vin?: string | null;
                      isActive?: boolean | null;
                      platformDealerId?: string | null;
                      coordinate?: number[] | null;
                      dealerName?: string | null;
                      vhrUrl?: string | null;
                      scoreCar?: number | null;
                      scoreDeal?: number | null;
                      standOutFeatures?: {
                        [key: string]: {
                            feature: string;
                            featureDetails: string;
                          }[];
                      } | null;
                    })[];
                })[]) | null;
              metadata?: ({
                availableGroupings?: string[] | null;
                availableSorting: string[];
                /** @enum {string|null} */
                currentGrouping?: "price_range" | "age" | "make_model" | "trim" | "mileage" | "body_style" | "score_car" | "score_deal" | null;
                /** @enum {string} */
                sortingField: "lastPrice" | "mileage" | "year" | "scoreCar" | "scoreDeal";
                /** @enum {string} */
                sortingDirection: "desc" | "asc";
                carIds?: string[];
                query?: {
                  [key: string]: unknown;
                } | null;
              }) | null;
              followUpQuestions?: string[] | null;
              searchResultIds?: string[] | null;
            };
          };
        };
      };
    };
  };
  "/api/public/search-result/{searchResultId}/follow-up-questions": {
    get: {
      parameters: {
        path: {
          searchResultId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              questions: string[];
            };
          };
        };
      };
    };
  };
  "/api/public/car/{carId}/better-deal/": {
    get: {
      parameters: {
        query?: {
          grouping?: "price_range" | "age" | "make_model" | "trim" | "mileage" | "body_style" | "score_car" | "score_deal" | null;
        };
        path: {
          carId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              count: number;
              /** Format: uuid */
              betterDealId: string;
            };
          };
        };
      };
    };
  };
  "/api/public/car/{carId}/better-deal/{betterDealId}": {
    get: {
      parameters: {
        path: {
          carId: string;
          betterDealId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              groupedCars?: (({
                  index: number;
                  name: string;
                  cars: ({
                      id: string;
                      make?: string | null;
                      model?: string | null;
                      year?: number | null;
                      mileage?: number | null;
                      price?: number | null;
                      images?: string[] | null;
                      features?: string[] | null;
                      body?: string | null;
                      color?: string | null;
                      shipping?: string | null;
                      dealerInfoStreet?: string | null;
                      dealerInfoCity?: string | null;
                      platformId?: string | null;
                      trim?: string | null;
                      vin?: string | null;
                      isActive?: boolean | null;
                      platformDealerId?: string | null;
                      coordinate?: number[] | null;
                      dealerName?: string | null;
                      vhrUrl?: string | null;
                      scoreCar?: number | null;
                      scoreDeal?: number | null;
                      standOutFeatures?: {
                        [key: string]: {
                            feature: string;
                            featureDetails: string;
                          }[];
                      } | null;
                    })[];
                })[]) | null;
            };
          };
        };
      };
    };
  };
  "/api/public/car/{carId}/car-scores/": {
    get: {
      parameters: {
        path: {
          carId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              car: {
                scoreAccident?: number | null;
                scoreCar?: number | null;
                scoreDeal?: number | null;
                scoreFeatures?: number | null;
                scoreMileage?: number | null;
                scorePrice?: number | null;
                scoreAccidentDetail?: string | null;
                scoreFeaturesDetail?: string | null;
                scoreMileageDetail?: string | null;
                scorePriceDetail?: string | null;
                scoreSummary?: string | null;
              };
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description - GENERAL_ERROR -> 1000
     * - CAR_SEARCH_LIMIT -> 1001
     * - SCOUT_REPORT_LIMIT -> 1002
     * - CAR_BETTER_DEAL_LIMIT -> 1003
     * - CAR_SCORE_LIMIT -> 1004
     * - DEALER_MESSAGE_LIMIT -> 1005
     * - BILLING_FAILED -> 1006
     * - BILLING_CANCEL_FAILED -> 1007
     * - BILLING_RENEWAL_FAILED -> 1008
     * - BILLING_DOWNGRADE_FAILED -> 1009
     * @enum {integer}
     */
    ErrorCodes: 1000 | 1001 | 1002 | 1003 | 1004 | 1005 | 1006 | 1007 | 1008 | 1009;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
