import '../config/env'
import { middleware } from './middleware'

import type { paths } from './schema/v1' // generated by openapi-typescript
import createClient from 'openapi-fetch'

const client = createClient<paths>({
  baseUrl: ENV.NEXT_PUBLIC_BASE_URL,
})

client.use(middleware)

export { client }
